version: '3.8'
services:
  web_service:
          container_name: web_service
          image: testgoapp-prod
          ports: 
            - '8080:8080'
          # volumes:
          # - ./web_service:/go/app